function VMENU:CreateUI()
    --Creates the main interface
        mainframe = CreateFrame("Button", "MiscMenuFrame", UIParent, nil)
        mainframe:SetSize(70,70)
        mainframe:EnableMouse(true)
        
        mainframe:RegisterForDrag("LeftButton")
        mainframe:SetScript("OnDragStart", function() mainframe:StartMoving() end)
        mainframe:SetScript("OnDragStop", function()
            mainframe:StopMovingOrSizing()
            self.db.menuPos = {mainframe:GetPoint()}
            self.db.menuPos[2] = "UIParent"
        end)
        mainframe:SetMovable(true)
        mainframe:RegisterForClicks("RightButtonDown")
        mainframe:SetScript("OnClick", function() if unlocked then self:UnlockFrame() end end)
        mainframe.icon = mainframe:CreateTexture(nil, "ARTWORK")
        mainframe.icon:SetSize(55,55)
        mainframe.icon:SetPoint("CENTER", mainframe,"CENTER",0,0)
        mainframe.icon:SetTexture(defIcon)
        mainframe.Text = mainframe:CreateFontString()
        mainframe.Text:SetFont("Fonts\\FRIZQT__.TTF", 13)
        mainframe.Text:SetFontObject(GameFontNormal)
        mainframe.Text:SetText("|cffffffffProf\nMenu")
        mainframe.Text:SetPoint("CENTER", mainframe.icon, "CENTER", 0, 0)
        mainframe.Highlight = mainframe:CreateTexture(nil, "OVERLAY")
        mainframe.Highlight:SetSize(70,70)
        mainframe.Highlight:SetPoint("CENTER", mainframe, 0, 0)
        mainframe.Highlight:SetTexture("Interface\\AddOns\\AwAddons\\Textures\\EnchOverhaul\\Slot2Selected")
        mainframe.Highlight:Hide()
        mainframe:Hide()
        mainframe:SetScript("OnEnter", function(button)
            if unlocked then
                GameTooltip:SetOwner(button, "ANCHOR_TOP")
                GameTooltip:AddLine("Left click to drag")
                GameTooltip:AddLine("Right click to lock frame")
                GameTooltip:Show()
            else
                self:ToggleMainButton("show")
            end
        end)
        mainframe:SetScript("OnLeave", function() GameTooltip:Hide() end)
    
        professionbutton = CreateFrame("Button", "MiscMenuFrame_Menu", MiscMenuFrame)
        professionbutton:SetSize(70,70)
        professionbutton:SetPoint("BOTTOM", MiscMenuFrame, "BOTTOM", 0, 2)
        professionbutton:RegisterForClicks("LeftButtonDown", "RightButtonDown")
        professionbutton:Show()
        professionbutton:SetScript("OnClick", function(button, btnclick) if not self.db.autoMenu then self:DewdropRegister(button, true) end end)
        professionbutton:SetScript("OnEnter", function(button)
            self:OnEnter(button, true)
            mainframe.Highlight:Show()
            self:ToggleMainButton("show")
        end)
        professionbutton:SetScript("OnLeave", function()
            mainframe.Highlight:Hide()
            GameTooltip:Hide()
            self:ToggleMainButton("hide")
        end)
    end
    Vanity_Menu:CreateUI()